#读写分离

spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    # 数据源配置
    datasource:
      # 数据源名称，多数据源以逗号分隔
      names: master,slave
      # 主库的datasource配置
      master:
        # 指定使用druid连接池
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://123.57.27.97:3306/order_01?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
        # 初始化大小，最小，最大
#        initialSize: 5
#        minIdle: 5
#        maxActive: 10
#        # 配置获取连接等待超时的时间
#        maxWait: 60000
#        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#        timeBetweenEvictionRunsMillis: 60000
#        # 配置一个连接在池中最小生存的时间，单位是毫秒
#        minEvictableIdleTimeMillis: 30000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        # 打开PSCache，并且指定每个连接上PSCache的大小
#        poolPreparedStatements: true
#        maxPoolPreparedStatementPerConnectionSize: 20
#        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#        filters: stat,wall,slf4j
#        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#        # 合并多个DruidDataSource的监控数据
#        #useGlobalDataSourceStat: true
#        web-stat-filter:
#          enabled: false
#          url-pattern: /*
#          exclusions: '*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*'
#        # Druid StatViewServlet配置 可视化web界面
#        stat-view-servlet:
#          enabled: true
#          url-pattern: /druid/*
#          reset-enable: true
#          login-username: admin
#          login-password: admin
#          # 配置日志输出
#        filter:
#          slf4j:
#            enabled: false
#            statement-create-after-log-enabled: false
#            result-set-open-after-log-enabled: false
#            result-set-close-after-log-enabled: false
      # 从库datasource配置
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: test
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://123.57.27.97:3307/order_01?useUnicode=true&characterEncoding=UTF-8
        username: test
    # 其他属性
    props:
      # 是否开启SQL显示，默认值: false
      sql:
        show: true
    sharding:
      #主库从库逻辑数据源定义 ds0为 order_01
      master-slave-rules:
        #逻辑数据源
        ds0:
          #主库
          master-data-source-name: master
          #从库
          slave-data-source-names: slave

logging:
  level:
    com:
      wdx:
        growingadmin: debug
    druid:
      sql: debug
    org:
      springframework:
        web: info
    root: info

#mybatis-plus配置
#mybatis-plus:
#  # 扫描mapper.xml文件
#  mapper-locations: classpath*:/mapper/*Mapper.xml
#  # 扫描实体类
##  typeAliasesPackage: com.example.springbootmybatisplus.entity
#  # 主键类型
#  global-config:
#    #0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 0
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 0
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #数据库大写下划线转换
##    capital-mode: true
#  #自定义SQL注入器
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: true
