#水平分表

spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    # 数据源配置
    datasource:
      # 数据源名称，多数据源以逗号分隔
      names: master
      # 主库的datasource配置
      master:
        # 指定使用druid连接池
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/order_1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
    # 其他属性
    props:
      # 是否开启SQL显示，默认值: false
      sql:
        show: true
    sharding:
      tables:
        #逻辑表名 sql语句表名（select * from order）
        order:
          #分表策略 配置数据节点 master.order_1,master.order_2
          actual-data-nodes: master.order_$->{1..2}
          table-strategy:
            inline:
              #分片键
              sharding-column: order_id
              #分片算法
              algorithm-expression: order_$->{order_id % 2 + 1}
          key-generator:
            #主键
            column: order_id
            #主键生成策略  雪花算法
            type: SNOWFLAKE


logging:
  level:
    com:
      wdx:
        growingadmin: debug
    druid:
      sql: debug
    org:
      springframework:
        web: info
    root: info
